### ISSUE TITLE
The training detail for UniAnimate

### ISSUE THREAD

**Issue by Sainzerjj** [ali-vilab/UniAnimate#55]
Great work! I have a few questions regarding the training process for Unianimate:

1. Should the training be conducted in phases, similar to Animate Anyone (two stages)?
2. If the training is done just in a single phase, are all parameters in both UNet and the pose guider updated simultaneously? Would this cause instability during training or lead to a decline in quality?
3. In the inference code (inference_unianimate_entrance.py), I noticed that classifier-free guidance is used. It seems that you set all conditions to None as "uncond" in classifier-free guidance. During training, do you randomly set all or some of the conditions to None with a certain probability to support this guidance? I am asking because I observed that in Animate Anyone, only the features encoded from ref_image are set to zero. Therefore, I am particularly interested in this operaion.

Deeply looking forward to your response！Thanks！

**Comment by wangxiang1230** [comment]
Hi, thanks for your attention.

1. We use a pretrained model TF-T2V as the initialization and only train our model on video data.
2. We fully-finetune the overall model. Since the model has a relatively good initialization, there is no instability and degradation.
3. We randomly set all or some of the conditions to None with a certain probability to support this guidance since we need to combine different conditions and want them to work individually (e.g., ['image','local_image', "dwpose"], ['image', 'randomref', "dwpose"]). You can refer to VideoComposer for more details. 

And we are considering open sourcing an upgraded version of the model in the near future (If the company allows it), which has a better appearance retention. Thanks for your attention.
